apiVersion: v1
kind: Secret
metadata:
  name: ngrok-secret
  labels:
    app: ngrok
type: Opaque
data:
  NGROK_AUTHTOKEN: Mm5xSWJCbkFKVnhoOHVUU3RvbEp0NW9MT2dSX2hxY1VBTVVpeDhOV1U0cEVidUtv  # Replace this with your base64-encoded token

