apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secret-binding
  namespace: ngrok-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secret-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops  # ArgoCD's namespace
