apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ngrok-dev
  name: argocd-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
