apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/muneerkh/ngrok-deployment'
    targetRevision: main
    path: overlays/dev
    kustomize:
      namePrefix: ngrok-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ngrok-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
